---
- hosts: localhost
  tasks:
  
  - name: Install Relevant Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - zsh
      - tmux
      - wget

  - name: Download ohMyZSH
    get_url: 
      url: https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh 
      dest: /tmp/zsh-installer.sh
      mode: 755

  - name: Run ohMyZSH installer
    shell: /tmp/zsh-installer.sh

  - name: Cleanup installer
    file: 
      path: /tmp/zsh-installer.sh
      state: absent

  - name: Set zsh as default shell
    shell: chsh -s /usr/bin/zsh "{{ user }}"
  
  - name: Install oh-my-zsh custom .zshrc file
    copy:
      src: "/home/{{ user }}/.oh-my-zsh/templates/zshrc.zsh-template"
      dest: "/home/{{ user }}/.zshrc"
      owner: "{{ user }}"
      owner: "{{ user }}"

