---
- hosts: localhost
  vars:
    oh_my_zsh_installed: False
  tasks:
  
  - name: Install Relevant Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - zsh
      - xclip
      - tmux
      - wget
      - curl
      - emacs
  
  - name: Check if myzsh is already installed
    stat:
      path: "/home/{{ user }}/.oh-my-zsh"
    register: oh_my_zsh_installed
  
  - name: do stuff
    include_tasks: install-oh-my-zsh.yml
    when: not oh_my_zsh_installed == True
  
  # Install default environment on machine
  - name: Clone repo into user's home directory
    become: yes
    become_user: "{{ user }}"
    git:
      repo: git@github.com:pamsilva/default-environment.git
      dest: "/home/{{ user }}/.default-environment"
      accept_hostkey: yes
      key_file: "/home/{{ user }}/.ssh/id_rsa"
 
 
  # Set up tmux 
  - name: Setting up tmux
    become: yes
    become_user: "{{ user }}"
    file:
      src: "/home/{{ user }}/.default-environment/tmux.conf"
      dest: "/home/{{ user }}/.tmux.conf"
      state: link

