---
- hosts: localhost
  tasks:
  
  - name: Install Relevant Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - zsh
      - tmux
      - wget
   
  # Handle the instalation of oh-my-zsh
  - name: Download oh-my-zsh
    get_url: 
      url: https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh 
      dest: /tmp/zsh-installer.sh
      mode: 755

  - name: Run oh-my-zsh installer
    shell: /tmp/zsh-installer.sh

  - name: Cleanup installer
    file: 
      path: /tmp/zsh-installer.sh
      state: absent

  - name: Set zsh as default shell
    shell: chsh -s /usr/bin/zsh "{{ user }}"
  
  - name: Install oh-my-zsh custom .zshrc file
    copy:
      src: "/home/{{ user }}/.oh-my-zsh/templates/zshrc.zsh-template"
      dest: "/home/{{ user }}/.zshrc"
      owner: "{{ user }}"
      group: "{{ user }}"
  
  # Install default environment on machine
  - name: Clone repo into user's home directory
    git:
      repo: git@github.com:pamsilva/default-environment.git
      dest: "/home/{{ user }}/.default-environment"
      key_file: "/home/{{ user }}/.ssh/id_rsa
 
  # Set up tmux 
  - name: Setting up tmux
    file:
      src: "/home/{{ user }}/.default-environment/tmux.conf"
      dest: "/home/{{ user }}/.tmux.conf"
      state: link

