---
- hosts: localhost
  tasks:
  
  - name: Install Relevant Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - zsh
      - tmux
      - wget
  
  - name: do stuff
    include_tasks: install-oh-my-zsh.yml
  
  # Install default environment on machine
  - name: Clone repo into user's home directory
    git:
      repo: git@github.com:pamsilva/default-environment.git
      dest: "/home/{{ user }}/.default-environment"
      key_file: "/home/{{ user }}/.ssh/id_rsa"
 
  # Set up tmux 
  - name: Setting up tmux
    file:
      src: "/home/{{ user }}/.default-environment/tmux.conf"
      dest: "/home/{{ user }}/.tmux.conf"
      state: link

